VirtoCommerce/vc-module-x-cart

- .deployment/module/cloudDeploy.json
> VCST-1551: Create cloudDeploy.json

- src/VirtoCommerce.XCart.Data/Middlewares/LoadCartToEvalContextMiddleware.cs
- src/VirtoCommerce.XCart.Data/Services/CartAggregateRepository.cs
- tests/VirtoCommerce.XCart.Tests/Repositories/CartAggregateRepositoryTests.cs
https://virtocommerce.atlassian.net/browse/VCST-1303
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.801.0-pr-3-5284.zip
> VCST-1303: add cache to CartAggregate repository

- src/VirtoCommerce.XCart.Core/CartAggregate.cs
feat: Adds a new FindExistingLineItemBeforeAdd method. It is responsible for finding an existing line item before adding a new one. If the method returns the line item, the new line item should be merged with the existing one.
When adding new line items to the cart, especially when dealing with dynamic properties (e.g., service configurations, T-shirt prints), it's important to ensure that duplicate items are not added. By default, line items are identified by their product ID. However, this implementation requires checking both the product ID and dynamic properties to determine if the line item already exists.
Steps to Use Dynamic Properties for Adding New Line Items:
1. Create a Custom VC Module: Set up a new module and add a dependency on VirtoCommerce.XCart or relevant packages.
2. …
> VCST-1564: Adds FindExistingLineItemBeforeAdd method

- src/VirtoCommerce.XCart.Core/VirtoCommerce.XCart.Core.csproj
- src/VirtoCommerce.XCart.Data/Queries/GetCartQueryBuilder.cs
- src/VirtoCommerce.XCart.Data/Queries/SearchCartQueryBuilder.cs
- src/VirtoCommerce.XCart.Data/Schemas/PurchaseSchema.cs
- src/VirtoCommerce.XCart.Data/VirtoCommerce.XCart.Data.csproj
- src/VirtoCommerce.XCart.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-1431
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.803.0-pr-7-cadc.zip
> VCST-1431: Ignore expired password when using external sign in

- src/VirtoCommerce.XCart.Core/Models/CartValidationError.cs
- src/VirtoCommerce.XCart.Core/Validators/CartErrorDescriber.cs
- src/VirtoCommerce.XCart.Data/Commands/AddCartItemsBulkCommandHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-1313
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.804.0-pr-2-350e.zip
> VCST-1313: check for duplicate product Skus on bulk add to cart

- src/VirtoCommerce.XCart.Data/Mapping/CartMappingProfile.cs
https://virtocommerce.atlassian.net/browse/VCST-1766
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.805.0-pr-10-1c22.zip
> VCST-1803: pass Cart currency to Tax evaluation context

- src/VirtoCommerce.XCart.Core/Specifications/PackSizeLimitSpecification.cs
- src/VirtoCommerce.XCart.Core/Validators/CartErrorDescriber.cs
- src/VirtoCommerce.XCart.Core/Validators/CartLineItemValidator.cs
- src/VirtoCommerce.XCart.Core/Validators/NewCartItemValidator.cs
- src/VirtoCommerce.XCart.Core/VirtoCommerce.XCart.Core.csproj
- src/VirtoCommerce.XCart.Web/module.manifest
feat: Added Pack Size Policy for cart operations.
https://virtocommerce.atlassian.net/browse/VCST-1811
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.807.0-pr-11-ec3a.zip
> VCST-1811: Implement Pack Size Limit

- src/VirtoCommerce.XCart.Core/CartAggregate.cs
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.810.0-pr-13-0347.zip
> fix: do not change validation errors collection

- src/VirtoCommerce.XCart.Core/Models/CartAggregateResponseGroup.cs
- src/VirtoCommerce.XCart.Data/Services/CartResponseGroupParser.cs
fix: Empty totals if shipment is requested
https://virtocommerce.atlassian.net/browse/VCST-2173
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.810.0-pr-15-51dc.zip
> VCST-2173: Empty totals if shipment is requested

- src/VirtoCommerce.XCart.Data/Authorization/CanAccessCartAuthorizationRequirement.cs
- src/VirtoCommerce.XCart.Data/VirtoCommerce.XCart.Data.csproj
- src/VirtoCommerce.XCart.Web/module.manifest
feat: Replace custom code with ClaimsPrincipalExtensions that resolves user id and name from IdentityOptions settings.
https://virtocommerce.atlassian.net/browse/VCST-2048
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.812.0-pr-16-fae1.zip
> VCST-2048: Use ClaimsPrincipalExtensions GetUserId

- src/VirtoCommerce.XCart.Core/Schemas/CartType.cs
- src/VirtoCommerce.XCart.Core/VirtoCommerce.XCart.Core.csproj
- src/VirtoCommerce.XCart.Web/module.manifest
Extended Cart Schema with CheckoutId
https://virtocommerce.atlassian.net/browse/VCST-2044
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.814.0-pr-17-858e.zip
> VCST-2044: Extended Cart Schema with CheckoutId

- src/VirtoCommerce.XCart.Core/VirtoCommerce.XCart.Core.csproj
- src/VirtoCommerce.XCart.Data/Commands/AddCartItemCommandHandler.cs
- src/VirtoCommerce.XCart.Data/Queries/GetProductConfigurationQueryHandler.cs
- src/VirtoCommerce.XCart.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-2223
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.817.0-pr-23-fa77.zip
> VCST-2223: update to Configurable Products

- src/VirtoCommerce.XCart.Core/VirtoCommerce.XCart.Core.csproj
- src/VirtoCommerce.XCart.Data/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.XCart.Web/Module.cs
- src/VirtoCommerce.XCart.Web/module.manifest
playground url: /ui/playground/cart
https://virtocommerce.atlassian.net/browse/VCST-2241
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.819.0-pr-21-5084.zip
> VCST-2241: add scoped schema

- src/VirtoCommerce.XCart.Web/Localizations/de.XCart.json
- src/VirtoCommerce.XCart.Web/Localizations/en.XCart.json
- src/VirtoCommerce.XCart.Web/Localizations/es.XCart.json
- src/VirtoCommerce.XCart.Web/Localizations/fr.XCart.json
- src/VirtoCommerce.XCart.Web/Localizations/it.XCart.json
- src/VirtoCommerce.XCart.Web/Localizations/ja.XCart.json
- src/VirtoCommerce.XCart.Web/Localizations/pl.XCart.json
- src/VirtoCommerce.XCart.Web/Localizations/pt.XCart.json
- src/VirtoCommerce.XCart.Web/Localizations/ru.XCart.json
- src/VirtoCommerce.XCart.Web/Localizations/zh.XCart.json
10 localization files
https://virtocommerce.atlassian.net/browse/VCST-2122
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.816.0-pr-20-eba0.zip
> 10 localization files

- src/VirtoCommerce.XCart.Core/Commands/CreateConfiguredLineItemCommand.cs
- src/VirtoCommerce.XCart.Core/ConfiguredLineItemContainer.cs
- src/VirtoCommerce.XCart.Core/Models/CartProductsRequest.cs
- src/VirtoCommerce.XCart.Core/Services/ICartProductsLoaderService.cs
- src/VirtoCommerce.XCart.Data/Commands/CreateConfiguredLineItemBuilder.cs
- src/VirtoCommerce.XCart.Data/Commands/CreateConfiguredLineItemHandler.cs
- src/VirtoCommerce.XCart.Data/Queries/GetProductConfigurationQueryHandler.cs
- src/VirtoCommerce.XCart.Data/Services/CartProductService.cs
https://virtocommerce.atlassian.net/browse/VCST-2466
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.822.0-pr-26-a931.zip
> VCST-2466: add discounts for configuration line item

- src/VirtoCommerce.XCart.Core/CartAggregate.cs
- src/VirtoCommerce.XCart.Core/Commands/AddCartItemCommand.cs
- src/VirtoCommerce.XCart.Core/Models/NewCartItem.cs
- src/VirtoCommerce.XCart.Core/Schemas/CartType.cs
- src/VirtoCommerce.XCart.Core/Schemas/InputAddItemType.cs
- src/VirtoCommerce.XCart.Data/Commands/AddCartItemCommandHandler.cs
- src/VirtoCommerce.XCart.Data/Commands/ChangeCartCurrencyCommandHandler.cs
From new to old.
https://virtocommerce.atlassian.net/browse/VCST-2473
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.824.0-pr-29-3712.zip
> VCST-2473: order cart line items

- Directory.Build.props
- src/VirtoCommerce.XCart.Core/CartAggregate.cs
- src/VirtoCommerce.XCart.Core/ConfiguredLineItemContainer.cs
- src/VirtoCommerce.XCart.Core/Models/CartProduct.cs
- src/VirtoCommerce.XCart.Core/VirtoCommerce.XCart.Core.csproj
- src/VirtoCommerce.XCart.Data/Mapping/CartMappingProfile.cs
- src/VirtoCommerce.XCart.Web/module.manifest
- tests/VirtoCommerce.XCart.Tests/Aggregates/CartAggregateTests.cs
- tests/VirtoCommerce.XCart.Tests/Handlers/MoveWishListItemCommandHandlerTests.cs
https://virtocommerce.atlassian.net/browse/VCST-2590
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.901.0-pr-30-af02.zip
> VCST-2590: add localized product name to line item

- src/VirtoCommerce.XCart.Core/ConfiguredLineItemContainer.cs
https://virtocommerce.atlassian.net/browse/VCST-2572
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.904.0-pr-33-96e6.zip
> VCST-2572: fix discount amount for configured item

- src/VirtoCommerce.XCart.Core/VirtoCommerce.XCart.Core.csproj
- src/VirtoCommerce.XCart.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-2589
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.905.0-pr-34-4111.zip
> VCST-2589: update Xapi dependency (Mediatr)

- src/VirtoCommerce.XCart.Core/CartAggregate.cs
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.912.0-pr-48-9943.zip
> fix: fix org name NRE

- src/VirtoCommerce.XCart.Core/ExpPricesSum.cs
- src/VirtoCommerce.XCart.Core/Queries/GetPricesSumQuery.cs
- src/VirtoCommerce.XCart.Core/Schemas/PricesSumType.cs
- src/VirtoCommerce.XCart.Data/Queries/GetPricesSumQueryBuilder.cs
- src/VirtoCommerce.XCart.Data/Queries/GetPricesSumQueryHandler.cs
```graphql
query pricesSum{
pricesSum(storeId:"Electronics", currencyCode: "USD", userId: "123", cultureName: "en-US", productIds: ["123","345"]) {
listPrice {
amount
}
salePrice {
amount
}
discountAmount {
amount
}
}
}
```
https://virtocommerce.atlassian.net/browse/VCST-2475
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.912.0-pr-45-f960.zip
> VCST-2475: add pricesSum query

- src/VirtoCommerce.XCart.Core/Validators/ConfigurationItemValidator.cs
https://virtocommerce.atlassian.net/browse/VCST-3274
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.914.0-pr-50-fa77.zip
> VCST-3274: Skip validation for config product without required options

- src/VirtoCommerce.XCart.Data/Commands/AddCartItemsBulkCommandHandler.cs
- src/VirtoCommerce.XCart.Data/Commands/AddWishlistBulkItemCommandHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-3414
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.916.0-pr-53-d352.zip
> VCST-3414: Make Bulk command handlers virtual

- src/VirtoCommerce.XCart.Core/VirtoCommerce.XCart.Core.csproj
- src/VirtoCommerce.XCart.Data/VirtoCommerce.XCart.Data.csproj
- src/VirtoCommerce.XCart.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-3299
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.918.0-pr-52-bc71.zip
> VCST-3299: Update catalog module

- src/VirtoCommerce.XCart.Core/Schemas/PaymentMethodType.cs
- src/VirtoCommerce.XCart.Core/VirtoCommerce.XCart.Core.csproj
- src/VirtoCommerce.XCart.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-3376
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.919.0-pr-51-2074.zip
> VCST-3376: Add localized name to PaymentMethodType

- src/VirtoCommerce.XCart.Core/Models/ExpCartPayment.cs
- src/VirtoCommerce.XCart.Core/Models/ExpCartShipment.cs
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.928.0-pr-67-fa56.zip
> fix: remove sealed attributes

- src/VirtoCommerce.XCart.Data/Services/CartAggregateRepository.cs
fix: Intermittent error when adding products to cart for anonymous users
https://virtocommerce.atlassian.net/browse/VCST-3779
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCart_3.935.0-pr-72-f335.zip
> VCST-3779: Intermittent error when adding products to cart for anonymous users
